from __future__ import annotations

import os
from pathlib import Path

from app_runtime import APP_BASE_DIR

ENV_PATH = APP_BASE_DIR / ".env"

DEFAULT_ENV = {
    "MZ_QQ_NUMBER": "",
    "MZ_DEBUGGER_ADDRESS": "127.0.0.1:9222",
    "MZ_CHROMEDRIVER_PATH": "",
    "MZ_CHROME_PATH": "",
    "MZ_CHROME_USER_DATA_DIR": "",
    "MZ_FRIEND_DATA_DIR": "",
    "MZ_RUN_LOG_DIR": "",
    "MZ_REMOTE_LOGIN_DATA_DIR": "",
}


def load_env_settings(path: Path | None = None) -> dict[str, str]:
    env_path = path or ENV_PATH
    data = dict(DEFAULT_ENV)
    if not env_path.is_file():
        return data

    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if key not in data:
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        data[key] = value
    return data


def save_env_settings(values: dict[str, str], path: Path | None = None) -> Path:
    env_path = path or ENV_PATH
    env_path.parent.mkdir(parents=True, exist_ok=True)
    merged = dict(DEFAULT_ENV)
    for key in merged:
        merged[key] = str(values.get(key, merged[key]) or "").strip()

    lines = [
        "# Generated by MZ control panel",
        f"MZ_QQ_NUMBER={merged['MZ_QQ_NUMBER']}",
        f"MZ_DEBUGGER_ADDRESS={merged['MZ_DEBUGGER_ADDRESS']}",
        f"MZ_CHROMEDRIVER_PATH={merged['MZ_CHROMEDRIVER_PATH']}",
        f"MZ_CHROME_PATH={merged['MZ_CHROME_PATH']}",
        f"MZ_CHROME_USER_DATA_DIR={merged['MZ_CHROME_USER_DATA_DIR']}",
        f"MZ_FRIEND_DATA_DIR={merged['MZ_FRIEND_DATA_DIR']}",
        f"MZ_RUN_LOG_DIR={merged['MZ_RUN_LOG_DIR']}",
        f"MZ_REMOTE_LOGIN_DATA_DIR={merged['MZ_REMOTE_LOGIN_DATA_DIR']}",
        "",
    ]
    env_path.write_text("\n".join(lines), encoding="utf-8")

    for key, value in merged.items():
        if value:
            os.environ[key] = value
        elif key in os.environ:
            del os.environ[key]
    return env_path
